#!/bin/bash
## SCRIPT PARA DETECTAR EL DISPOSITIVO DE AUDIO HDMI
## FECHA: 10 de mayo de 2020

if aplay --list-devices | grep HDMI &> /dev/null; then
	if [[ $(aplay --list-devices | grep HDMI | head -n 1 | tail -n 1) == $(aplay --list-devices | grep HDMI | head -n 2 | tail -n 1) ]]; then
		HDMI_AUDIO=$(aplay --list-devices | grep HDMI | grep -o '..................$' | cut -c 1)
	else
		HDMI_AUDIO=$(aplay --list-devices | grep HDMI | head -n $1 | tail -n 1 | grep -o '..................$' | cut -c 1)
	fi
else
	HDMI_AUDIO=none
fi

echo $HDMI_AUDIO
