#!/bin/bash
## WRAPPER PARA EJECUTAR JUEGOS CON WINE
## FECHA DE CREACIÓN: 3 de enero de 2020
## FECHAS DE MODIFICACIÓN: 

dir=$(dirname "$1")
[ ! -d "$dir" ] && echo "[ERROR] Directorio inválido" && exit 1
[ ! -f "$1" ] && echo "[ERROR] Archivo no encontrado" && exit 1

cd "$dir"
wine "$1"

