#!/bin/bash
## SCRIPT QUE ES LLAMADO EN LUGAR DE exo-open CUANDO KDE-CONNECT RECIBE LINKS O ARCHIVOS
## FECHA DE CREACIÓN: 3 de noviembre de 2020

DPI=$(xfconf-query -c xsettings -p /Xft/DPI)
notify-send ENVIO "$@"
if [[ $DPI == "129" ]]; then

	## CASO 1: LINK NORMAL
	if echo $1 | grep "http"; then
		## CASO 1A: YOUTUBE - HAY QUE PROCESARLO PARA QUE SE ABRA EN YOUTUBE TV
		if echo $1 | grep "youtu.be" || echo $1 | grep "youtube.com"; then
			modoTV-handler -a $1
			exit $?
		
		## CASO 1B: LINK NORMAL - ABRIR DEL TIRÓN
		else
			modoTV-handler -l $1
			exit $?
					
		fi
	else
	
		## CASO 2: NOS COMPARTEN UNA CADENA CON UN LINK INCRUSTADO Y HAY QUE PROCESARLO 
		if echo $1 | grep "file:///tmp/kdeconnectd"; then
			modoTV-handler -s $1
			exit $?
		else
			
			## CASO 3: ????
			true
		fi
	fi
else

	## NO ESTAMOS EN MODO TV, LLAMAMOS AL exo-open POR DEFECTO DE XFCE
	/usr/bin/exo-open $@
	exit $?
fi
