#!/bin/bash

WIFI=$(/sbin/iw dev wlo1 info | grep ssid | awk '{print $2}')

if [[ $WIFI == "vodafone1B20" ]]; then
	/usr/bin/kdeconnect-handler $@
else
	notify-send --icon=dialog-warning "INFO" "No se podrá usar KDE Connect en esta red Wi-Fi."
	exit 1
fi
