#!/bin/bash
## ENCENDER O APAGAR LA PANTALLA DEL #pcgrande EN XUBUNTU AL PULSAR Fn+F7
## FECHA DE CREACIÓN: 19 de agosto de 2020
## FECHAS DE MODIFICACIÓN: 

if [[ ! -f ~/.edp1off ]]; then
	touch  ~/.edp1off
	notify-send --icon=display "PANTALLA DEL PORTÁTIL" "La pantalla se va a apagar"
	sleep 1.5
	xrandr --output eDP1 --off
elif [[  -f ~/.edp1off ]]; then
	rm ~/.edp1off
	xrandr --output eDP1 --auto
	notify-send --icon=display "PANTALLA DEL PORTÁTIL" "La pantalla se ha restaurado correctamente"
fi

exit 0
