#!/bin/bash
## SCRIPT COMPLEMENTO DE "anclar-documentos", PARA CARGAR ARCHIVOS ANCLADOS DESDE EL MENÚ DIRECTAMENTE
## FECHA: 1 de agosto de 2019

if [ -f "$1" ]; then
	xdg-open "$1"
else
	anclar-documentos "$1" non-existent
fi
