#!/bin/bash
## A EFECTOS DEL BATOCERA, DETECTAR QUE PC ES ESTE
## FECHA: 10 de mayo de 2020

case $(cat /sys/devices/virtual/dmi/id/board_name) in
	X541UJ) echo pcgrande;;
	82A9) echo pcazul;;
	"NPVAA DDR3") echo armatoste;;
	*) echo default;;
esac
exit 0
